// Turns docs/phase-1/design-tokens.json (Phase 1, approved) into consumable outputs:
//   - packages/design-tokens/dist/tokens.css         (CSS custom properties, light + dark, for apps/admin)
//   - packages/flutter_core/lib/theme/tokens.g.dart  (Dart constants, for the two Flutter apps)
// Re-run after any change to the source token file; both outputs are generated, not hand-edited.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = dirname(dirname(fileURLToPath(import.meta.url))); // packages/design-tokens
const repoRoot = dirname(dirname(packageDir)); // repo root
const tokens = JSON.parse(readFileSync(join(repoRoot, "docs/phase-1/design-tokens.json"), "utf8"));

// Token values can alias a palette entry as "{brand.cedar-500}" or "{neutral.50}" (see color.light
// / color.dark). Both namespaces live under color, so resolution is always tokens.color[ns][key].
const REF = /^\{([\w-]+)\.([\w-]+)\}$/;
function resolveRefs<T>(node: T): T {
  if (typeof node === "string") {
    const m = REF.exec(node);
    if (!m) return node;
    // Both groups are always captured when REF matches (neither is optional in the pattern).
    const ns = m[1]!;
    const key = m[2]!;
    const resolved = tokens.color?.[ns]?.[key];
    if (resolved === undefined) {
      throw new Error(`Unresolvable design token reference: ${node}`);
    }
    return resolved as T;
  }
  if (Array.isArray(node)) return node.map(resolveRefs) as T;
  if (node !== null && typeof node === "object") {
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, resolveRefs(v)])) as T;
  }
  return node;
}

const resolved = resolveRefs(tokens);

type Leaf = string | number;
function flatten(obj: unknown, prefix: string[] = []): Array<[string[], Leaf]> {
  if (obj === null || typeof obj !== "object") {
    return [[prefix, obj as Leaf]];
  }
  return Object.entries(obj as Record<string, unknown>).flatMap(([k, v]) =>
    k.startsWith("$") ? [] : flatten(v, [...prefix, k]),
  );
}

function cssVarName(path: string[]): string {
  return `--wsl-${path.join("-")}`;
}

// Each path segment may itself be kebab-case ("font-family", "cedar-500"); split on "-" too so
// every piece becomes its own capitalized word, keeping the result a legal Dart identifier.
function toWords(path: string[]): string[] {
  return path.flatMap((segment) => segment.split("-"));
}

function dartConstName(path: string[]): string {
  const [first, ...rest] = toWords(path);
  const name = first + rest.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
  // A pure-numeric first word ("0", "1", ...) would still start with a digit-first identifier
  // only if the whole path were numeric, which no top-level token group is; guard anyway.
  return /^[0-9]/.test(name) ? `t${name}` : name;
}

function toCssValue(v: Leaf): string {
  return typeof v === "number" ? String(v) : v;
}

// --- split into light palette / dark palette / everything else -----------------------------
const flatAll = flatten(resolved);
const lightEntries = flatAll.filter(([p]) => p[0] === "color" && p[1] === "light");
const darkEntries = flatAll.filter(([p]) => p[0] === "color" && p[1] === "dark");
const sharedEntries = flatAll.filter(
  ([p]) => !(p[0] === "color" && (p[1] === "light" || p[1] === "dark")),
);

// --- CSS output ------------------------------------------------------------------------------
function cssBlock(entries: Array<[string[], Leaf]>, pathOffset: number): string {
  return entries.map(([p, v]) => `  ${cssVarName(p.slice(pathOffset))}: ${toCssValue(v)};`).join("\n");
}

const css = `/* Generated by packages/design-tokens/src/generate.ts from docs/phase-1/design-tokens.json. Do not hand-edit. */
:root {
${cssBlock(sharedEntries, 0)}
${cssBlock(lightEntries, 1)}
}

:root[data-theme="dark"] {
${cssBlock(darkEntries, 1)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${cssBlock(darkEntries, 1)}
  }
}
`;

const cssOutDir = join(packageDir, "dist");
mkdirSync(cssOutDir, { recursive: true });
writeFileSync(join(cssOutDir, "tokens.css"), css);

// --- Dart output -----------------------------------------------------------------------------
function hexToDartColor(hex: string): string | undefined {
  const m = /^#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.exec(hex);
  if (!m) return undefined;
  const captured = m[1]!; // the single group always matches when m is non-null
  const digits = captured.length === 6 ? `FF${captured}` : captured; // 6 digits = opaque, prefix full alpha
  return `Color(0x${digits.toUpperCase()})`;
}

function dartLine([p, v]: [string[], Leaf]): string {
  const name = dartConstName(p);
  if (typeof v === "number") {
    return `  static const double ${name} = ${v};`;
  }
  const color = hexToDartColor(v);
  if (color) {
    return `  static const Color ${name} = ${color};`;
  }
  return `  static const String ${name} = '${v.replace(/'/g, "\\'")}';`;
}

const dartLightBody = lightEntries.map(([p, v]) => dartLine([p.slice(2), v])).join("\n");
const dartDarkBody = darkEntries.map(([p, v]) => dartLine([p.slice(2), v])).join("\n");
const dartSharedBody = sharedEntries.map(dartLine).join("\n");

const dart = `// Generated by packages/design-tokens/src/generate.ts from docs/phase-1/design-tokens.json.
// Do not hand-edit; re-run \`pnpm --filter @wasselne/design-tokens run generate\`.
import 'package:flutter/material.dart';

class WasselneTokens {
${dartSharedBody}
}

class WasselneLightColors {
${dartLightBody}
}

class WasselneDarkColors {
${dartDarkBody}
}
`;

const dartOutDir = join(repoRoot, "packages", "flutter_core", "lib", "theme");
mkdirSync(dartOutDir, { recursive: true });
writeFileSync(join(dartOutDir, "tokens.g.dart"), dart);
try {
  // Best effort: keeps `dart format --set-exit-if-changed` green where the Dart SDK exists.
  execFileSync("dart", ["format", join(dartOutDir, "tokens.g.dart")], { stdio: "ignore" });
} catch {
  /* Dart SDK not installed (e.g. TypeScript-only CI job): leave the file unformatted. */
}

console.log("Wrote dist/tokens.css and ../flutter_core/lib/theme/tokens.g.dart");
