-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- Wasselne — Phase 2 schema (design contract).
-- Target: PostgreSQL 16 + PostGIS 3.4. Phase 3 splits this into ordered migrations.
-- Conventions: UUID keys; timestamptz in UTC; money = bigint minor units + currency code;
-- rates/percentages = integer basis points (10000 = 100% or ×1.0). Localized text = jsonb {"ar","en","fr"}.
-- See 02_State_Machines_and_Transactions.md for the transaction rules these constraints back up.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS citext;

-- ---------------------------------------------------------------- enums
CREATE TYPE gender              AS ENUM ('FEMALE','MALE');
CREATE TYPE app_language        AS ENUM ('ar','en','fr');
CREATE TYPE app_kind            AS ENUM ('RIDER','DRIVER');
CREATE TYPE account_status      AS ENUM ('ACTIVE','DELETED');
CREATE TYPE vehicle_base_type   AS ENUM ('CAR','MOTORCYCLE','TUKTUK');
CREATE TYPE publish_status      AS ENUM ('DRAFT','PUBLISHED','RETIRED');
CREATE TYPE driver_status       AS ENUM ('ONBOARDING','SUBMITTED','NEEDS_CHANGES','APPROVED','REJECTED','SUSPENDED');
CREATE TYPE approval_status     AS ENUM ('PENDING','APPROVED','REJECTED','PAUSED_BY_DRIVER');
CREATE TYPE document_status     AS ENUM ('UPLOADED','APPROVED','NEEDS_CHANGES','REJECTED','EXPIRED','SUPERSEDED');
CREATE TYPE vehicle_check_status AS ENUM ('DUE','SUBMITTED','APPROVED','NEEDS_CHANGES');
CREATE TYPE upload_status       AS ENUM ('AUTHORIZED','COMPLETED','QUARANTINED','REJECTED','EXPIRED');
CREATE TYPE fare_mode           AS ENUM ('FIXED','RECALCULATE');
CREATE TYPE value_kind          AS ENUM ('FIXED','PERCENT');
CREATE TYPE discount_kind       AS ENUM ('PROMO_CODE','AUTOMATIC');
CREATE TYPE redemption_status   AS ENUM ('RESERVED','CONSUMED','RELEASED');
CREATE TYPE ride_status         AS ENUM ('SEARCHING','CONFIRMED','AT_PICKUP','IN_PROGRESS','COMPLETED',
                                         'NO_DRIVER','CANCELLED','NO_SHOW','ELIGIBILITY_MISMATCH');
CREATE TYPE actor_role          AS ENUM ('RIDER','DRIVER','ADMIN','SYSTEM');
CREATE TYPE offer_state         AS ENUM ('PENDING_ACK','ACTIVE','ACCEPTED','DECLINED','EXPIRED','CANCELLED');
CREATE TYPE offer_end_reason    AS ENUM ('ACK_TIMEOUT','ACCEPT_TIMEOUT','DECLINED','ACCEPTED',
                                         'RIDE_CANCELLED','RIDE_ASSIGNED','DRIVER_INELIGIBLE');
CREATE TYPE payment_status      AS ENUM ('NOT_DUE','DUE','CHARGE_PENDING','CHARGE_FAILED','RECORDED',
                                         'DISPUTED','RESOLVED','VOID');
CREATE TYPE ledger_entry_type   AS ENUM ('COMMISSION','DISCOUNT_COMPENSATION','ADJUSTMENT','REVERSAL',
                                         'PAYOUT','SETTLEMENT');
CREATE TYPE translation_status  AS ENUM ('PENDING','DONE','FAILED');
CREATE TYPE case_type           AS ENUM ('LOST_ITEM','MESS_DAMAGE','FARE_PAYMENT','DRIVER_BEHAVIOUR',
                                         'RIDER_BEHAVIOUR','SAFETY','ELIGIBILITY_MISMATCH','APP','OTHER');
CREATE TYPE case_status         AS ENUM ('OPEN','IN_REVIEW','WAITING_USER','RESOLVED','CLOSED');
CREATE TYPE sos_status          AS ENUM ('RECEIVED','AGENT_JOINED','AGENT_CALLING','RESOLVED');
CREATE TYPE delivery_status     AS ENUM ('QUEUED','SENT','FAILED','NOT_APPLICABLE');
CREATE TYPE review_direction    AS ENUM ('RIDER_TO_DRIVER','DRIVER_TO_RIDER');
CREATE TYPE legal_doc_type      AS ENUM ('TERMS','PRIVACY','DRIVER_AGREEMENT','CANCELLATION','OTHER');
