-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- reference data
CREATE TABLE currencies (
  code            char(3) PRIMARY KEY,            -- 'USD','LBP'
  minor_exponent  smallint NOT NULL CHECK (minor_exponent BETWEEN 0 AND 3)
);

-- One versioned document holding all CMS platform parameters (ACK timeout, search duration,
-- phone window, payment %, payout triggers, commission switch, published currencies, ...).
-- JSON schema validated in the application; a ride stores the version it was created under.
CREATE TABLE platform_settings_versions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  settings        jsonb NOT NULL,
  status          publish_status NOT NULL DEFAULT 'DRAFT',
  effective_at    timestamptz,
  created_by      uuid,
  published_by    uuid,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CHECK (status <> 'PUBLISHED' OR (effective_at IS NOT NULL AND published_by IS NOT NULL))
);
CREATE INDEX ON platform_settings_versions (status, effective_at DESC);
