-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- identity
CREATE TABLE accounts (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_e164            text NOT NULL UNIQUE CHECK (phone_e164 ~ '^\+[1-9][0-9]{6,14}$'),
  first_name            text,
  last_name             text,
  gender                gender,
  gender_confirmed_at   timestamptz,                 -- D-39 management confirmation
  gender_confirmed_by   uuid,
  email                 citext,
  language              app_language NOT NULL DEFAULT 'ar',
  preferred_currency    char(3) REFERENCES currencies(code),
  status                account_status NOT NULL DEFAULT 'ACTIVE',
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER accounts_touch BEFORE UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE rider_profiles (
  account_id      uuid PRIMARY KEY REFERENCES accounts(id),
  rating_avg_bp   integer,                           -- cached average ×100 (e.g. 482 = 4.82)
  rating_count    integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE otp_challenges (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_e164      text NOT NULL,
  code_hash       text NOT NULL,                     -- never store the code in clear text
  provider_ref    text,
  attempts        smallint NOT NULL DEFAULT 0,
  expires_at      timestamptz NOT NULL,
  consumed_at     timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON otp_challenges (phone_e164, created_at DESC);

CREATE TABLE sessions (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id          uuid NOT NULL REFERENCES accounts(id),
  app                 app_kind NOT NULL,
  refresh_token_hash  text NOT NULL UNIQUE,          -- rotated on every refresh
  device_label        text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  last_used_at        timestamptz,
  expires_at          timestamptz NOT NULL,
  revoked_at          timestamptz,
  revoke_reason       text
);
CREATE INDEX ON sessions (account_id) WHERE revoked_at IS NULL;

CREATE TABLE push_devices (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id      uuid NOT NULL REFERENCES accounts(id),
  app             app_kind NOT NULL,
  platform        text NOT NULL CHECK (platform IN ('android','ios')),
  token           text NOT NULL UNIQUE,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Blocks (D-34, D-41). effective_at NULL = pending until the account's active ride ends.
CREATE TABLE account_blocks (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id      uuid NOT NULL REFERENCES accounts(id),
  applies_to      app_kind[] NOT NULL,               -- {RIDER}, {DRIVER} or both
  reason          text NOT NULL,
  created_by      uuid NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  effective_at    timestamptz,
  lifted_at       timestamptz,
  lifted_by       uuid,
  lift_reason     text
);
CREATE INDEX ON account_blocks (account_id) WHERE lifted_at IS NULL;
