-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- admin
CREATE TABLE admin_users (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email               citext NOT NULL UNIQUE,
  full_name           text NOT NULL,
  password_hash       text NOT NULL,                 -- argon2id
  totp_secret_enc     bytea,                         -- encrypted; NULL until MFA enrolled
  mfa_enrolled_at     timestamptz,
  status              text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DEACTIVATED')),
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_recovery_codes (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id        uuid NOT NULL REFERENCES admin_users(id),
  code_hash       text NOT NULL,
  used_at         timestamptz
);

CREATE TABLE admin_roles (
  code            text PRIMARY KEY,                  -- SUPER_ADMIN, DRIVER_REVIEWER, OPERATIONS, PRICING, ...
  permissions     text[] NOT NULL                    -- e.g. {'rides.read','chat.view','accounts.block'}
);

CREATE TABLE admin_user_roles (
  admin_id        uuid NOT NULL REFERENCES admin_users(id),
  role_code       text NOT NULL REFERENCES admin_roles(code),
  granted_by      uuid,
  granted_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (admin_id, role_code)
);

CREATE TABLE admin_sessions (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id            uuid NOT NULL REFERENCES admin_users(id),
  token_hash          text NOT NULL UNIQUE,
  mfa_verified_at     timestamptz,
  ip                  inet,
  created_at          timestamptz NOT NULL DEFAULT now(),
  expires_at          timestamptz NOT NULL,
  revoked_at          timestamptz
);

-- Append-only audit of every admin mutation and every sensitive read (chat, documents, evidence).
CREATE TABLE admin_audit_log (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  admin_id        uuid NOT NULL,
  action          text NOT NULL,                     -- 'driver.approve', 'chat.view', ...
  target_type     text NOT NULL,
  target_id       text NOT NULL,
  reason          text,
  before_state    jsonb,
  after_state     jsonb,
  ip              inet,
  correlation_id  text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON admin_audit_log (target_type, target_id, created_at DESC);
CREATE INDEX ON admin_audit_log (admin_id, created_at DESC);
CREATE TRIGGER admin_audit_log_immutable BEFORE UPDATE OR DELETE ON admin_audit_log
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
