-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- legal documents (D-22)
CREATE TABLE legal_document_versions (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_type                legal_doc_type NOT NULL,
  audience                app_kind[] NOT NULL,
  version_no              integer NOT NULL,
  requires_reacceptance   boolean NOT NULL DEFAULT false,
  status                  publish_status NOT NULL DEFAULT 'DRAFT',
  published_at            timestamptz,
  published_by            uuid,
  created_at              timestamptz NOT NULL DEFAULT now(),
  UNIQUE (doc_type, version_no)
);

CREATE TABLE legal_document_texts (
  version_id      uuid NOT NULL REFERENCES legal_document_versions(id),
  language        app_language NOT NULL,
  title           text NOT NULL,
  body_markdown   text NOT NULL,
  change_summary  text,
  PRIMARY KEY (version_id, language)
);

CREATE TABLE legal_acceptances (
  account_id      uuid NOT NULL REFERENCES accounts(id),
  version_id      uuid NOT NULL REFERENCES legal_document_versions(id),
  app             app_kind NOT NULL,
  accepted_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (account_id, version_id)
);
