-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- categories & documents (D-24)
CREATE TABLE document_types (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code            text NOT NULL UNIQUE,
  names           jsonb NOT NULL,
  subject         text NOT NULL CHECK (subject IN ('DRIVER','VEHICLE')),
  has_expiry      boolean NOT NULL DEFAULT false,
  allow_gallery   boolean NOT NULL DEFAULT true,
  active          boolean NOT NULL DEFAULT true
);

CREATE TABLE vehicle_categories (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code                    text NOT NULL UNIQUE,      -- 'car','motorcycle','tuktuk','women_taxi',...
  names                   jsonb NOT NULL,
  descriptions            jsonb,
  base_type               vehicle_base_type NOT NULL,
  seats                   smallint NOT NULL CHECK (seats > 0),
  female_drivers_only     boolean NOT NULL DEFAULT false,   -- D-35
  female_riders_only      boolean NOT NULL DEFAULT false,
  vehicle_rules           jsonb NOT NULL DEFAULT '{}',      -- e.g. {"min_year":2015}
  icon                    text NOT NULL,
  color                   text,
  sort_order              integer NOT NULL DEFAULT 0,
  active                  boolean NOT NULL DEFAULT false,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER vehicle_categories_touch BEFORE UPDATE ON vehicle_categories FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE category_document_requirements (
  category_id         uuid NOT NULL REFERENCES vehicle_categories(id),
  document_type_id    uuid NOT NULL REFERENCES document_types(id),
  PRIMARY KEY (category_id, document_type_id)
);
