-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- service zones (D-14)
CREATE TABLE service_zones (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code            text NOT NULL UNIQUE,
  name            text NOT NULL,
  active          boolean NOT NULL DEFAULT false,
  priority        integer NOT NULL DEFAULT 0,       -- higher wins where polygons overlap
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE service_zone_versions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  zone_id         uuid NOT NULL REFERENCES service_zones(id),
  geom            geometry(MultiPolygon, 4326) NOT NULL CHECK (ST_IsValid(geom)),
  status          publish_status NOT NULL DEFAULT 'DRAFT',
  effective_at    timestamptz,
  published_by    uuid,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX service_zone_versions_geom ON service_zone_versions USING gist (geom) WHERE status = 'PUBLISHED';
CREATE UNIQUE INDEX one_published_version_per_zone ON service_zone_versions (zone_id) WHERE status = 'PUBLISHED';

CREATE TABLE zone_category_settings (
  zone_id             uuid NOT NULL REFERENCES service_zones(id),
  category_id         uuid NOT NULL REFERENCES vehicle_categories(id),
  enabled             boolean NOT NULL DEFAULT false,
  search_radius_m     integer NOT NULL DEFAULT 5000 CHECK (search_radius_m BETWEEN 200 AND 50000),
  PRIMARY KEY (zone_id, category_id)
);
