-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- drivers & vehicles
CREATE TABLE driver_profiles (
  account_id          uuid PRIMARY KEY REFERENCES accounts(id),
  status              driver_status NOT NULL DEFAULT 'ONBOARDING',
  status_reason       text,
  submitted_at        timestamptz,
  decided_at          timestamptz,
  decided_by          uuid,
  current_vehicle_id  uuid,
  rating_avg_bp       integer,
  rating_count        integer NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER driver_profiles_touch BEFORE UPDATE ON driver_profiles FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE vehicles (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id       uuid NOT NULL REFERENCES driver_profiles(account_id),
  base_type       vehicle_base_type NOT NULL,
  make            text NOT NULL,
  model           text NOT NULL,
  year            smallint,
  color           text NOT NULL,
  plate           text NOT NULL,
  seats           smallint NOT NULL CHECK (seats > 0),
  active          boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX vehicles_plate_active ON vehicles (upper(plate)) WHERE active;
ALTER TABLE driver_profiles ADD FOREIGN KEY (current_vehicle_id) REFERENCES vehicles(id);

CREATE TABLE driver_category_approvals (
  driver_id       uuid NOT NULL REFERENCES driver_profiles(account_id),
  category_id     uuid NOT NULL REFERENCES vehicle_categories(id),
  vehicle_id      uuid NOT NULL REFERENCES vehicles(id),
  status          approval_status NOT NULL DEFAULT 'PENDING',
  reason          text,
  decided_by      uuid,
  decided_at      timestamptz,
  PRIMARY KEY (driver_id, category_id)
);

CREATE TABLE uploads (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_account_id    uuid NOT NULL REFERENCES accounts(id),
  purpose             text NOT NULL CHECK (purpose IN ('DRIVER_DOCUMENT','PROFILE_PHOTO','VEHICLE_CHECK','CASE_EVIDENCE')),
  object_key          text NOT NULL UNIQUE,
  content_type        text NOT NULL,
  max_bytes           integer NOT NULL,
  size_bytes          integer,
  sha256              text,
  status              upload_status NOT NULL DEFAULT 'AUTHORIZED',
  expires_at          timestamptz NOT NULL,
  completed_at        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE driver_documents (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id           uuid NOT NULL REFERENCES driver_profiles(account_id),
  vehicle_id          uuid REFERENCES vehicles(id),
  document_type_id    uuid NOT NULL REFERENCES document_types(id),
  upload_id           uuid NOT NULL REFERENCES uploads(id),
  expires_on          date,
  status              document_status NOT NULL DEFAULT 'UPLOADED',
  review_reason       text,
  reviewed_by         uuid,
  reviewed_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);
-- One current (non-superseded, non-rejected) document per driver/vehicle/type.
CREATE UNIQUE INDEX one_current_document ON driver_documents
  (driver_id, coalesce(vehicle_id, '00000000-0000-0000-0000-000000000000'::uuid), document_type_id)
  WHERE status IN ('UPLOADED','APPROVED','NEEDS_CHANGES');

CREATE TABLE vehicle_checks (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id      uuid NOT NULL REFERENCES vehicles(id),
  due_on          date NOT NULL,
  status          vehicle_check_status NOT NULL DEFAULT 'DUE',
  submitted_at    timestamptz,
  reviewed_by     uuid,
  reviewed_at     timestamptz,
  review_reason   text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX one_open_check_per_vehicle ON vehicle_checks (vehicle_id) WHERE status IN ('DUE','SUBMITTED','NEEDS_CHANGES');

CREATE TABLE vehicle_check_photos (
  check_id        uuid NOT NULL REFERENCES vehicle_checks(id),
  slot            text NOT NULL,                     -- 'front','back','left','right','interior',...
  upload_id       uuid NOT NULL REFERENCES uploads(id),
  PRIMARY KEY (check_id, slot)
);

CREATE TABLE driver_online_sessions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id       uuid NOT NULL REFERENCES driver_profiles(account_id),
  started_at      timestamptz NOT NULL DEFAULT now(),
  ended_at        timestamptz,
  end_reason      text
);
CREATE UNIQUE INDEX one_open_online_session ON driver_online_sessions (driver_id) WHERE ended_at IS NULL;
