-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- rider places
CREATE TABLE saved_places (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rider_id        uuid NOT NULL REFERENCES rider_profiles(account_id),
  label           text NOT NULL CHECK (length(label) BETWEEN 1 AND 60),
  icon            text,
  address_text    text,
  location        geography(Point, 4326) NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON saved_places (rider_id);
