-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- pricing (D-15, D-20, D-25, D-26)
CREATE TABLE tariff_versions (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id                 uuid NOT NULL REFERENCES vehicle_categories(id),
  zone_id                     uuid NOT NULL REFERENCES service_zones(id),
  currency                    char(3) NOT NULL REFERENCES currencies(code),
  base_minor                  bigint NOT NULL CHECK (base_minor >= 0),
  per_km_minor                bigint NOT NULL CHECK (per_km_minor >= 0),
  per_minute_minor            bigint NOT NULL CHECK (per_minute_minor >= 0),
  minimum_minor               bigint NOT NULL CHECK (minimum_minor >= 0),
  rounding_increment_minor    bigint NOT NULL DEFAULT 1 CHECK (rounding_increment_minor > 0),
  fare_mode                   fare_mode NOT NULL DEFAULT 'FIXED',
  recalc_cap_bp               integer CHECK (recalc_cap_bp BETWEEN 0 AND 10000),
  status                      publish_status NOT NULL DEFAULT 'DRAFT',
  effective_at                timestamptz,
  created_by                  uuid,
  published_by                uuid,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  CHECK (fare_mode = 'FIXED' OR recalc_cap_bp IS NOT NULL)
);
CREATE INDEX tariff_lookup ON tariff_versions (category_id, zone_id, currency, effective_at DESC) WHERE status = 'PUBLISHED';

CREATE TABLE surge_rules (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  zone_id         uuid NOT NULL REFERENCES service_zones(id),
  category_id     uuid REFERENCES vehicle_categories(id),   -- NULL = all categories in zone
  multiplier_bp   integer NOT NULL CHECK (multiplier_bp BETWEEN 10000 AND 50000),
  starts_at       timestamptz NOT NULL,
  ends_at         timestamptz NOT NULL CHECK (ends_at > starts_at),
  active          boolean NOT NULL DEFAULT true,
  created_by      uuid NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON surge_rules (zone_id, starts_at, ends_at) WHERE active;

CREATE TABLE addons (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code            text NOT NULL UNIQUE,
  names           jsonb NOT NULL,
  kind            value_kind NOT NULL,
  currency        char(3) REFERENCES currencies(code),      -- required for FIXED
  amount_minor    bigint CHECK (amount_minor >= 0),
  percent_bp      integer CHECK (percent_bp BETWEEN 0 AND 10000),
  zone_id         uuid REFERENCES service_zones(id),
  category_id     uuid REFERENCES vehicle_categories(id),
  schedule        jsonb,                                     -- optional days/hours
  starts_at       timestamptz,
  ends_at         timestamptz,
  active          boolean NOT NULL DEFAULT false,
  created_by      uuid NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CHECK ((kind = 'FIXED' AND currency IS NOT NULL AND amount_minor IS NOT NULL)
      OR (kind = 'PERCENT' AND percent_bp IS NOT NULL))
);

CREATE TABLE discounts (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind                    discount_kind NOT NULL,
  code                    citext UNIQUE,                     -- promo code; NULL for AUTOMATIC
  names                   jsonb NOT NULL,
  value_kind              value_kind NOT NULL,
  percent_bp              integer CHECK (percent_bp BETWEEN 1 AND 10000),
  currency                char(3) REFERENCES currencies(code),
  amount_minor            bigint CHECK (amount_minor > 0),
  max_discount_minor      jsonb,                             -- {"USD":200,"LBP":180000}
  zone_ids                uuid[],                            -- NULL = all zones
  category_ids            uuid[],                            -- NULL = all categories
  starts_at               timestamptz NOT NULL,
  ends_at                 timestamptz NOT NULL CHECK (ends_at > starts_at),
  total_limit             integer,
  per_rider_limit         integer,
  platform_share_bp       integer NOT NULL DEFAULT 10000 CHECK (platform_share_bp BETWEEN 0 AND 10000), -- D-31
  active                  boolean NOT NULL DEFAULT false,
  created_by              uuid NOT NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  CHECK ((kind = 'PROMO_CODE') = (code IS NOT NULL)),
  CHECK ((value_kind = 'PERCENT' AND percent_bp IS NOT NULL)
      OR (value_kind = 'FIXED' AND currency IS NOT NULL AND amount_minor IS NOT NULL))
);

CREATE TABLE commission_rules (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id     uuid NOT NULL REFERENCES vehicle_categories(id),
  zone_id         uuid REFERENCES service_zones(id),         -- NULL = all zones
  rate_bp         integer NOT NULL CHECK (rate_bp BETWEEN 0 AND 10000),
  status          publish_status NOT NULL DEFAULT 'DRAFT',
  effective_at    timestamptz,
  published_by    uuid,
  created_at      timestamptz NOT NULL DEFAULT now()
);
