-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- quotes & rides
CREATE TABLE quotes (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rider_id                uuid NOT NULL REFERENCES rider_profiles(account_id),
  category_id             uuid NOT NULL REFERENCES vehicle_categories(id),
  zone_id                 uuid NOT NULL REFERENCES service_zones(id),
  pickup                  geography(Point, 4326) NOT NULL,
  dropoff                 geography(Point, 4326) NOT NULL,
  pickup_text             text,
  dropoff_text            text,
  route_distance_m        integer NOT NULL,
  route_duration_s        integer NOT NULL,
  route_polyline          text,
  surge_rule_id           uuid REFERENCES surge_rules(id),
  surge_multiplier_bp     integer NOT NULL DEFAULT 10000,
  discount_id             uuid REFERENCES discounts(id),
  settings_version_id     uuid NOT NULL REFERENCES platform_settings_versions(id),
  expires_at              timestamptz NOT NULL,
  used_at                 timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON quotes (rider_id, created_at DESC);

CREATE TABLE quote_amounts (
  quote_id            uuid NOT NULL REFERENCES quotes(id),
  currency            char(3) NOT NULL REFERENCES currencies(code),
  tariff_version_id   uuid NOT NULL REFERENCES tariff_versions(id),
  gross_minor         bigint NOT NULL,
  discount_minor      bigint NOT NULL DEFAULT 0,
  total_minor         bigint NOT NULL CHECK (total_minor >= 0),
  breakdown           jsonb NOT NULL,     -- base, distance, time, surge, addons[], minimum_adjustment, discount, rounding
  PRIMARY KEY (quote_id, currency)
);

CREATE TABLE rides (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rider_id                    uuid NOT NULL REFERENCES rider_profiles(account_id),
  quote_id                    uuid NOT NULL UNIQUE REFERENCES quotes(id),
  request_idempotency_key     text NOT NULL,
  category_id                 uuid NOT NULL REFERENCES vehicle_categories(id),
  category_snapshot           jsonb NOT NULL,         -- names, icon, base_type, women-only flags at request time
  zone_id                     uuid NOT NULL REFERENCES service_zones(id),
  pickup                      geography(Point, 4326) NOT NULL,
  dropoff                     geography(Point, 4326) NOT NULL,
  pickup_text                 text,
  dropoff_text                text,
  status                      ride_status NOT NULL DEFAULT 'SEARCHING',
  version                     integer NOT NULL DEFAULT 1,
  settings_version_id         uuid NOT NULL REFERENCES platform_settings_versions(id),
  fare_mode                   fare_mode NOT NULL,
  recalc_cap_bp               integer,
  payment_request_pct         smallint NOT NULL DEFAULT 100 CHECK (payment_request_pct BETWEEN 1 AND 100), -- D-28
  commission_counted          boolean NOT NULL,       -- D-42 snapshot of the CMS switch
  commission_rate_bp          integer NOT NULL DEFAULT 0,
  discount_id                 uuid REFERENCES discounts(id),
  discount_platform_share_bp  integer,
  search_deadline_at          timestamptz NOT NULL,
  next_dispatch_at            timestamptz,
  dispatch_attempts           integer NOT NULL DEFAULT 0,
  requested_at                timestamptz NOT NULL DEFAULT now(),
  confirmed_at                timestamptz,
  arrived_at                  timestamptz,
  started_at                  timestamptz,
  completed_at                timestamptz,
  ended_at                    timestamptz,
  actual_distance_m           integer,
  actual_duration_s           integer,
  end_actor                   actor_role,
  end_reason                  text,
  UNIQUE (rider_id, request_idempotency_key)
);
CREATE UNIQUE INDEX one_active_ride_per_rider ON rides (rider_id)
  WHERE status IN ('SEARCHING','CONFIRMED','AT_PICKUP','IN_PROGRESS');
CREATE INDEX rides_dispatch_due ON rides (next_dispatch_at) WHERE status = 'SEARCHING';
CREATE INDEX rides_search_deadline ON rides (search_deadline_at) WHERE status = 'SEARCHING';
CREATE INDEX ON rides (rider_id, requested_at DESC);

CREATE TABLE ride_fares (
  ride_id                 uuid NOT NULL REFERENCES rides(id),
  currency                char(3) NOT NULL REFERENCES currencies(code),
  tariff_version_id       uuid NOT NULL REFERENCES tariff_versions(id),
  quoted_gross_minor      bigint NOT NULL,
  quoted_discount_minor   bigint NOT NULL,
  quoted_total_minor      bigint NOT NULL,
  final_total_minor       bigint,                     -- set at completion (= quoted in FIXED mode)
  quoted_breakdown        jsonb NOT NULL,
  final_breakdown         jsonb,
  PRIMARY KEY (ride_id, currency)
);

CREATE TABLE ride_offers (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id             uuid NOT NULL REFERENCES rides(id),
  driver_id           uuid NOT NULL REFERENCES driver_profiles(account_id),
  vehicle_id          uuid NOT NULL REFERENCES vehicles(id),
  attempt_no          integer NOT NULL,
  driver_attempt_no   smallint NOT NULL,
  state               offer_state NOT NULL DEFAULT 'PENDING_ACK',
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
  ack_deadline_at     timestamptz NOT NULL,
  acknowledged_at     timestamptz,
  accept_deadline_at  timestamptz,
  resolved_at         timestamptz,
  end_reason          offer_end_reason,
  UNIQUE (ride_id, attempt_no),
  CHECK (state <> 'ACTIVE' OR (acknowledged_at IS NOT NULL
         AND accept_deadline_at = acknowledged_at + interval '3 seconds')),
  CHECK ((state IN ('PENDING_ACK','ACTIVE')) = (resolved_at IS NULL))
);
CREATE UNIQUE INDEX one_outstanding_offer_per_ride   ON ride_offers (ride_id)   WHERE state IN ('PENDING_ACK','ACTIVE');
CREATE UNIQUE INDEX one_outstanding_offer_per_driver ON ride_offers (driver_id) WHERE state IN ('PENDING_ACK','ACTIVE');
CREATE INDEX offers_ack_due    ON ride_offers (ack_deadline_at)    WHERE state = 'PENDING_ACK';
CREATE INDEX offers_accept_due ON ride_offers (accept_deadline_at) WHERE state = 'ACTIVE';
CREATE INDEX ON ride_offers (ride_id, driver_id);

CREATE TABLE ride_assignments (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id         uuid NOT NULL REFERENCES rides(id),
  driver_id       uuid NOT NULL REFERENCES driver_profiles(account_id),
  vehicle_id      uuid NOT NULL REFERENCES vehicles(id),
  offer_id        uuid NOT NULL UNIQUE REFERENCES ride_offers(id),
  vehicle_snapshot jsonb NOT NULL,                    -- make, model, colour, plate at assignment
  assigned_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
  ended_at        timestamptz,
  outcome         text
);
CREATE UNIQUE INDEX one_open_assignment_per_ride   ON ride_assignments (ride_id)   WHERE ended_at IS NULL;
CREATE UNIQUE INDEX one_open_assignment_per_driver ON ride_assignments (driver_id) WHERE ended_at IS NULL;

CREATE TABLE ride_events (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ride_id         uuid NOT NULL REFERENCES rides(id),
  ride_version    integer NOT NULL,
  from_status     ride_status,
  to_status       ride_status NOT NULL,
  actor_role      actor_role NOT NULL,
  actor_id        uuid,
  reason          text,
  created_at      timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX ON ride_events (ride_id, id);
CREATE TRIGGER ride_events_immutable BEFORE UPDATE OR DELETE ON ride_events
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

-- Sampled trip trail (not every GPS update). Retention per policy (TBD, legal review).
CREATE TABLE trip_location_samples (
  ride_id         uuid NOT NULL REFERENCES rides(id),
  captured_at     timestamptz NOT NULL,
  location        geography(Point, 4326) NOT NULL,
  accuracy_m      real,
  PRIMARY KEY (ride_id, captured_at)
);

CREATE TABLE discount_redemptions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  discount_id     uuid NOT NULL REFERENCES discounts(id),
  rider_id        uuid NOT NULL REFERENCES rider_profiles(account_id),
  ride_id         uuid NOT NULL UNIQUE REFERENCES rides(id),
  status          redemption_status NOT NULL DEFAULT 'RESERVED',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON discount_redemptions (discount_id, rider_id) WHERE status <> 'RELEASED';
