-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- payments & ledger (D-28..D-31, D-38, D-42, D-43)
CREATE TABLE payment_methods (
  code                text PRIMARY KEY,               -- 'cash','omt','whish','bank','card'
  names               jsonb NOT NULL,
  enabled             boolean NOT NULL DEFAULT false,
  adapter_available   boolean NOT NULL DEFAULT false, -- set by deployment, not by CMS users
  config_enc          bytea,
  updated_by          uuid,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CHECK (NOT enabled OR adapter_available)
);

CREATE TABLE ride_payments (
  ride_id                 uuid PRIMARY KEY REFERENCES rides(id),
  method_code             text NOT NULL REFERENCES payment_methods(code),
  status                  payment_status NOT NULL DEFAULT 'NOT_DUE',
  due_at                  timestamptz,
  recorded_currency       char(3) REFERENCES currencies(code),
  recorded_amount_minor   bigint CHECK (recorded_amount_minor >= 0),
  recorded_by             uuid,
  recorded_at             timestamptz,
  discrepancy_reason      text,
  tip_currency            char(3) REFERENCES currencies(code),   -- information only (D-42)
  tip_amount_minor        bigint CHECK (tip_amount_minor >= 0),
  resolution              text,
  resolved_by             uuid,
  resolved_at             timestamptz,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CHECK (status NOT IN ('RECORDED','DISPUTED') OR (recorded_currency IS NOT NULL AND recorded_amount_minor IS NOT NULL))
);

-- Driver wallet ledger. Positive amount = Wasselne owes the driver.
CREATE TABLE ledger_entries (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  driver_id           uuid NOT NULL REFERENCES driver_profiles(account_id),
  currency            char(3) NOT NULL REFERENCES currencies(code),
  amount_minor        bigint NOT NULL CHECK (amount_minor <> 0),
  entry_type          ledger_entry_type NOT NULL,
  ride_id             uuid REFERENCES rides(id),
  payout_id           uuid,
  settlement_id       uuid,
  reverses_entry_id   bigint REFERENCES ledger_entries(id),
  reason              text,
  created_by          uuid,                            -- NULL = system
  idempotency_key     text NOT NULL UNIQUE,            -- e.g. 'ride:{id}:COMMISSION'
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (entry_type NOT IN ('ADJUSTMENT','REVERSAL') OR reason IS NOT NULL),
  CHECK (entry_type <> 'REVERSAL' OR reverses_entry_id IS NOT NULL)
);
CREATE INDEX ON ledger_entries (driver_id, currency, id);
CREATE TRIGGER ledger_entries_immutable BEFORE UPDATE OR DELETE ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

CREATE VIEW driver_wallet_balances AS
  SELECT driver_id, currency, sum(amount_minor)::bigint AS balance_minor, max(created_at) AS last_entry_at
  FROM ledger_entries GROUP BY driver_id, currency;

CREATE TABLE payouts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id       uuid NOT NULL REFERENCES driver_profiles(account_id),
  currency        char(3) NOT NULL REFERENCES currencies(code),
  amount_minor    bigint NOT NULL CHECK (amount_minor > 0),
  method          text NOT NULL,                       -- TBD; free text until methods are defined
  reference       text,
  recorded_by     uuid NOT NULL,
  paid_at         timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE settlement_methods (
  code            text PRIMARY KEY,                    -- 'payout_deduction','cash_pickup',...
  names           jsonb NOT NULL,
  enabled         boolean NOT NULL DEFAULT false,
  instructions    jsonb,
  updated_by      uuid,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE driver_settlements (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id       uuid NOT NULL REFERENCES driver_profiles(account_id),
  currency        char(3) NOT NULL REFERENCES currencies(code),
  amount_minor    bigint NOT NULL CHECK (amount_minor > 0),
  method_code     text NOT NULL REFERENCES settlement_methods(code),
  reference       text,
  recorded_by     uuid NOT NULL,
  collected_at    timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ledger_entries ADD FOREIGN KEY (payout_id) REFERENCES payouts(id);
ALTER TABLE ledger_entries ADD FOREIGN KEY (settlement_id) REFERENCES driver_settlements(id);
