-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- chat (BR-31/32, D-33)
CREATE TABLE chat_messages (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id             uuid NOT NULL REFERENCES rides(id),
  sender_id           uuid NOT NULL REFERENCES accounts(id),
  sender_role         actor_role NOT NULL CHECK (sender_role IN ('RIDER','DRIVER')),
  client_message_id   text NOT NULL,
  body                text NOT NULL CHECK (length(body) BETWEEN 1 AND 2000),
  source_language     text,
  seen_at             timestamptz,
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (sender_id, client_message_id)
);
CREATE INDEX ON chat_messages (ride_id, created_at);

CREATE TABLE chat_translations (
  message_id          uuid NOT NULL REFERENCES chat_messages(id),
  target_language     app_language NOT NULL,
  text                text,
  status              translation_status NOT NULL DEFAULT 'PENDING',
  provider            text,
  error               text,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, target_language)
);
