-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- support & SOS (BR-33..37, 47..49, D-17, D-21)
CREATE TABLE support_cases (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_type           case_type NOT NULL,
  ride_id             uuid REFERENCES rides(id),
  reporter_id         uuid NOT NULL REFERENCES accounts(id),
  reporter_role       actor_role NOT NULL,
  status              case_status NOT NULL DEFAULT 'OPEN',
  subject             text,
  assigned_admin_id   uuid REFERENCES admin_users(id),
  resolution          text,
  resolved_by         uuid,
  resolved_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CHECK (status NOT IN ('RESOLVED','CLOSED') OR resolution IS NOT NULL)
);
CREATE INDEX ON support_cases (status, created_at);
CREATE INDEX ON support_cases (ride_id);

CREATE TABLE case_messages (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id             uuid NOT NULL REFERENCES support_cases(id),
  author_account_id   uuid REFERENCES accounts(id),
  author_admin_id     uuid REFERENCES admin_users(id),
  client_message_id   text,
  body                text NOT NULL,
  internal_note       boolean NOT NULL DEFAULT false,  -- staff-only
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK ((author_account_id IS NULL) <> (author_admin_id IS NULL))
);

CREATE TABLE case_evidence (
  case_id         uuid NOT NULL REFERENCES support_cases(id),
  upload_id       uuid NOT NULL REFERENCES uploads(id),
  added_by        uuid NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (case_id, upload_id)
);

CREATE TABLE sos_config_versions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  config          jsonb NOT NULL,    -- {actions:["AGENT_CHAT"], fallback_number, oncall_channels, hours, escalation_s}
  status          publish_status NOT NULL DEFAULT 'DRAFT',
  effective_at    timestamptz,
  published_by    uuid,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE support_agent_presence (
  admin_id        uuid PRIMARY KEY REFERENCES admin_users(id),
  on_shift_since  timestamptz NOT NULL,
  last_seen_at    timestamptz NOT NULL
);

CREATE TABLE sos_incidents (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id                 uuid REFERENCES rides(id),
  reporter_id             uuid NOT NULL REFERENCES accounts(id),
  reporter_role           actor_role NOT NULL,
  client_request_id       text NOT NULL,
  sos_config_version_id   uuid NOT NULL REFERENCES sos_config_versions(id),
  location                geography(Point, 4326),
  location_captured_at    timestamptz,
  status                  sos_status NOT NULL DEFAULT 'RECEIVED',
  assigned_agent_id       uuid REFERENCES admin_users(id),
  agent_joined_at         timestamptz,
  agent_calling_at        timestamptz,
  no_agent_fallback       boolean NOT NULL DEFAULT false,
  oncall_alert_status     delivery_status NOT NULL DEFAULT 'NOT_APPLICABLE',
  resolution              text,
  resolved_at             timestamptz,
  created_at              timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (reporter_id, client_request_id)
);
CREATE INDEX ON sos_incidents (status, created_at) WHERE status <> 'RESOLVED';

CREATE TABLE sos_messages (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id         uuid NOT NULL REFERENCES sos_incidents(id),
  author_account_id   uuid REFERENCES accounts(id),
  author_admin_id     uuid REFERENCES admin_users(id),
  client_message_id   text,
  body                text NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK ((author_account_id IS NULL) <> (author_admin_id IS NULL))
);
