-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- reviews (BR-38..40, D-37)
CREATE TABLE reviews (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ride_id                 uuid NOT NULL REFERENCES rides(id),
  direction               review_direction NOT NULL,
  reviewer_id             uuid NOT NULL REFERENCES accounts(id),
  reviewee_id             uuid NOT NULL REFERENCES accounts(id),
  rating                  smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment                 text CHECK (length(comment) <= 1000),
  tags                    text[],
  declared_tip_currency   char(3) REFERENCES currencies(code),   -- rider-declared, information only
  declared_tip_minor      bigint CHECK (declared_tip_minor >= 0),
  moderation_status       text NOT NULL DEFAULT 'VISIBLE' CHECK (moderation_status IN ('VISIBLE','HIDDEN')),
  moderated_by            uuid,
  created_at              timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ride_id, direction),
  CHECK (reviewer_id <> reviewee_id)
);
