-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- reliability plumbing
CREATE TABLE idempotency_keys (
  actor_id            uuid NOT NULL,
  operation           text NOT NULL,
  key                 text NOT NULL,
  request_hash        text NOT NULL,
  response_status     smallint,
  response_body       jsonb,
  created_at          timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (actor_id, operation, key)
);

CREATE TABLE outbox_events (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_id            uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  aggregate_type      text NOT NULL,
  aggregate_id        uuid NOT NULL,
  aggregate_version   integer,
  event_type          text NOT NULL,
  payload             jsonb NOT NULL,
  available_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
  claimed_until       timestamptz,
  attempts            smallint NOT NULL DEFAULT 0,
  processed_at        timestamptz,
  last_error          text,
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX outbox_pending ON outbox_events (available_at) WHERE processed_at IS NULL;

CREATE TABLE delivery_attempts (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  outbox_event_id     bigint NOT NULL REFERENCES outbox_events(id),
  channel             text NOT NULL CHECK (channel IN ('SOCKET','PUSH','SMS','EMAIL')),
  target_account_id   uuid,
  status              delivery_status NOT NULL,
  provider_ref        text,
  error               text,
  created_at          timestamptz NOT NULL DEFAULT clock_timestamp()
);
