-- Generated by scripts/split-schema.mjs from docs/phase-2/schema.sql (do not hand-edit the split; edit the source and re-run).
-- ---------------------------------------------------------------- seed reference rows (no prices, no legal text)
INSERT INTO currencies (code, minor_exponent) VALUES ('USD', 2), ('LBP', 0);
INSERT INTO payment_methods (code, names, enabled, adapter_available) VALUES
  ('cash',  '{"en":"Cash","ar":"نقداً","fr":"Espèces"}', true,  true),
  ('omt',   '{"en":"OMT","ar":"OMT","fr":"OMT"}',       false, false),
  ('whish', '{"en":"Whish","ar":"Whish","fr":"Whish"}', false, false),
  ('bank',  '{"en":"Bank","ar":"مصرف","fr":"Banque"}',  false, false),
  ('card',  '{"en":"Card","ar":"بطاقة","fr":"Carte"}',  false, false);
INSERT INTO settlement_methods (code, names) VALUES
  ('payout_deduction', '{"en":"Deduct from payout","ar":"خصم من الدفعة","fr":"Déduction du versement"}'),
  ('cash_pickup',      '{"en":"Cash pickup","ar":"استلام نقدي","fr":"Collecte en espèces"}');
