// The design tokens CSS is generated by @wasselne/design-tokens (not committed); copy it next to
// the app so Next can import it. Run automatically before dev and build.
import { copyFileSync, existsSync } from "node:fs";
const src = new URL("../../../packages/design-tokens/dist/tokens.css", import.meta.url);
if (!existsSync(src)) {
  console.error("tokens.css missing: run `pnpm --filter @wasselne/design-tokens run generate` first.");
  process.exit(1);
}
copyFileSync(src, new URL("../app/tokens.generated.css", import.meta.url));
